const {chromium}=require('C:/Users/rhesa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const page=await browser.newPage({viewport:{width:1500,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');await page.waitForSelector('.element');assert.equal(await page.locator('.element').count(),118);
const data=vm.runInNewContext(fs.readFileSync('dist/elements.js','utf8')+';elements');
assert.equal(new Set(data.map(e=>`${e.row}:${e.col}`)).size,118);assert.deepEqual(Array.from({length:7},(_,i)=>data.filter(e=>e.period===i+1).length),[2,8,8,18,18,32,32]);
for(const e of data){assert(e.mass&&!e.mass.includes('&'));assert(e.col>=1&&e.col<=18);assert(e.valence>=1&&e.valence<=12);await page.locator(`[data-number="${e.number}"]`).click();assert.equal(await page.locator('#element-name').textContent(),e.name);const vals=await page.locator('.property dd').allTextContents();assert.equal(vals[0],String(e.number));assert.equal(vals[1],e.mass+(e.mass.startsWith('[')?'':' u'));assert.equal(vals[2],String(e.period));assert.equal(vals[3],String(e.number));assert.equal(vals[4],String(e.valence));assert.equal(vals[5],e.symbol);await page.keyboard.press('Escape');}
for(const [q,expected]of [['oxygen',8],['Au',79],['118',118],['aluminum',13]]){await page.locator('#search').fill(q);assert.equal(await page.locator('.element:not(:disabled)').count(),1);assert.equal(await page.locator('.element:not(:disabled)').getAttribute('data-number'),String(expected));}await page.locator('#search').fill('not-an-element');assert.equal(await page.locator('.element:not(:disabled)').count(),0);assert(await page.locator('#empty').isVisible());await page.locator('#reset').click();
for(const p of [1,2,3,4,5,6,7]){await page.selectOption('#period',String(p));assert.equal(await page.locator('.element:not(:disabled)').count(),data.filter(e=>e.period===p).length);}await page.locator('#reset').click();
for(const cat of new Set(data.map(e=>e.category))){await page.selectOption('#category',cat);assert.equal(await page.locator('.element:not(:disabled)').count(),data.filter(e=>e.category===cat).length);}await page.selectOption('#category','Noble gas');await page.selectOption('#period','2');assert.equal(await page.locator('.element:not(:disabled)').getAttribute('data-number'),'10');await page.locator('#reset').click();
await page.locator('[data-number="1"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator(':focus').getAttribute('data-number'),'2');await page.keyboard.press('Enter');assert(await page.locator('#detail').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator(':focus').getAttribute('data-number'),'2');await page.locator('[data-number="1"]').click();assert(await page.locator('#previous').isDisabled());await page.locator('#next').click();assert.equal(await page.locator('#element-name').textContent(),'Helium');await page.keyboard.press('Escape');
await page.screenshot({path:'desktop.png',fullPage:true});
for(const width of [390,768]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-number="118"]').click();assert(await page.locator('#element-name').isVisible());const r=await page.locator('#detail').boundingBox();assert(r.x>=0&&r.x+r.width<=width);if(width===390)await page.screenshot({path:'mobile-detail.png'});await page.keyboard.press('Escape');await page.locator('#search').fill('iron');assert.equal(await page.locator('.element:not(:disabled)').count(),1);await page.locator('#reset').click();}
await page.setViewportSize({width:750,height:600});await page.evaluate(()=>document.documentElement.style.fontSize='32px');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-number="103"]').click();await page.screenshot({path:'large-text.png'});await page.keyboard.press('Escape');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: all 118 selectable profiles, complete property readback, unique positions, period totals, every category/period filter, combined filtering, search/aliases/empty/reset, keyboard/modal focus, navigation, desktop/tablet/mobile and 200% text checks.');})().catch(e=>{console.error(e);process.exit(1)});

